
package aplicacionformulario;


public class ComboBox extends javax.swing.JFrame {

    /**
     * Creates new form ComboBox
     */
    public ComboBox() {
        initComponents();
        cargaDatos();
    }
    
    public void cargaDatos(){
        jComboBoxpaises.addItem("Seleccione un pais");
        jComboBoxpaises.addItem("Argentina");
        jComboBoxpaises.addItem("Peru");
        jComboBoxpaises.addItem("Colombia");
        jComboBoxpaises.addItem("Chile");
        jComboBoxpaises.addItem("Venezuela");
        jComboBoxpaises.addItem("Paraguay");
        jComboBoxpaises.addItem("Ecuador");
        
       
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxciudad = new javax.swing.JComboBox<>();
        jComboBoxpaises = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxciudadActionPerformed(evt);
            }
        });

        jComboBoxpaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxpaisesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jComboBoxpaises, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(jComboBoxciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxpaises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxpaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxpaisesActionPerformed
        // TODO add your handling code here:
        jComboBoxciudad.removeAllItems();
        
        if (jComboBoxpaises.getSelectedItem()=="Colombia") {
            jComboBoxciudad.addItem("Ingrese la ciudad");
            jComboBoxciudad.addItem("Medellin");
            jComboBoxciudad.addItem("Bogota");
            jComboBoxciudad.addItem("Cali");
            jComboBoxciudad.addItem("Cartagena");
            jComboBoxciudad.addItem("Barranquilla");
            jComboBoxciudad.addItem("Santa Marta");
            
        }
        else if (jComboBoxpaises.getSelectedItem()=="Argentina") {
            
            jComboBoxciudad.addItem("Ingrese la ciudad");
            jComboBoxciudad.addItem("Buenos Aires");
            jComboBoxciudad.addItem("La plata");
            jComboBoxciudad.addItem("Tucuman");
            
            
        }
        else if (jComboBoxpaises.getSelectedIndex()==2) {
            jComboBoxciudad.addItem("la paz");
            jComboBoxciudad.addItem("chicua");
            
        }
{
            
        }
    }//GEN-LAST:event_jComboBoxpaisesActionPerformed

    private void jComboBoxciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxciudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxciudad;
    private javax.swing.JComboBox<String> jComboBoxpaises;
    // End of variables declaration//GEN-END:variables
}
